import React from 'react';
import { ArrowLeft, ShieldCheck } from 'lucide-react';

type LegalPageKind = 'privacy' | 'legal' | 'cookies';
const placeholders = '[À COMPLÉTER]';
const pageContent: Record<LegalPageKind, { title: string; intro: string }> = {
  privacy: { title: 'Politique de confidentialité', intro: 'Cette politique décrit les données traitées lorsque vous utilisez le site de la Résidence NOEMA et ses formulaires.' },
  legal: { title: 'Mentions légales', intro: 'Les informations signalées par un emplacement à compléter doivent être validées par Uriel Group avant publication définitive.' },
  cookies: { title: 'Politique des cookies', intro: 'Le site privilégie une utilisation sans suivi publicitaire. Les technologies décrites ci-dessous sont limitées à celles réellement présentes dans le projet.' },
};

export const LegalPage: React.FC<{ kind: LegalPageKind }> = ({ kind }) => {
  const content = pageContent[kind];
  const goBack = () => window.history.length > 1 ? window.history.back() : window.location.assign('/');
  return <main className="min-h-screen bg-[#fbf8f2] text-[#5b3a2e]"><div className="mx-auto max-w-4xl px-5 py-8 sm:px-8 sm:py-14">
    <button type="button" onClick={goBack} className="mb-12 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.16em] text-[#d15a3a] hover:underline"><ArrowLeft className="h-4 w-4" /> Retour au site</button>
    <div className="mb-12 border-b border-[#e5c9b1] pb-8"><div className="mb-4 flex items-center gap-2 text-xs font-bold uppercase tracking-[0.2em] text-[#d15a3a]"><ShieldCheck className="h-4 w-4" /> Résidence NOEMA</div><h1 className="font-serif text-4xl font-bold leading-tight sm:text-6xl">{content.title}</h1><p className="mt-5 max-w-2xl text-base leading-relaxed text-neutral-600">{content.intro}</p><p className="mt-4 text-xs font-semibold uppercase tracking-wider text-neutral-500">Dernière mise à jour : 23 septembre 2026</p></div>
    {kind === 'privacy' && <PrivacyContent />}{kind === 'legal' && <LegalContent />}{kind === 'cookies' && <CookieContent />}
  </div></main>;
};

const Section: React.FC<{ title: string; children: React.ReactNode }> = ({ title, children }) => <section className="mb-10"><h2 className="mb-3 font-serif text-2xl font-bold text-[#5b3a2e]">{title}</h2><div className="space-y-3 text-sm leading-7 text-neutral-700">{children}</div></section>;

const PrivacyContent = () => <><Section title="Responsable du traitement"><p>Le responsable du traitement est Uriel Group, exploitant commercial de la Résidence NOEMA. Adresse officielle : {placeholders}. Contact protection des données : {placeholders}.</p></Section><Section title="Données collectées"><p>Les formulaires peuvent recueillir votre nom, prénom, email, téléphone/WhatsApp, pays de résidence et les informations nécessaires à une demande de financement ou de rendez-vous. Les données de simulation et les paramètres de campagne transmis par le site peuvent également être enregistrés.</p><p>La connexion à un espace utilisateur peut utiliser des données de compte et des cookies de session. Aucun outil d’analyse publicitaire n’est installé dans le code audité.</p></Section><Section title="Finalités et base du traitement"><p>Ces informations servent à répondre à votre demande, préparer une étude indicative, organiser un rendez-vous et assurer le suivi commercial demandé. Le traitement repose sur votre demande et, lorsque le formulaire le prévoit, sur votre consentement explicite. Le consentement marketing est facultatif et peut être retiré.</p></Section><Section title="Conservation, destinataires et prestataires"><p>Les données sont accessibles aux personnes habilitées d’Uriel Group et aux prestataires techniques nécessaires au fonctionnement du site, de l’hébergement, de la messagerie ou de l’authentification, lorsqu’ils sont effectivement utilisés. Durées de conservation : {placeholders}, à confirmer avec Uriel Group et selon les obligations applicables.</p></Section><Section title="Vos droits"><p>Vous pouvez demander l’accès, la rectification, l’effacement, la limitation ou la portabilité de vos données, ou vous opposer à certains traitements. Écrivez à {placeholders} en précisant votre demande et un moyen de vous recontacter. Vous pouvez également saisir l’autorité de contrôle compétente.</p></Section><Section title="Sécurité et évolutions"><p>Le site met en œuvre des contrôles d’accès, une protection CSRF sur les parcours authentifiés et des mesures de sécurité côté serveur. Aucune sécurité ne pouvant être absolue, toute demande sensible doit être adressée via un canal confirmé. Cette politique pourra être mise à jour ; sa date de dernière mise à jour sera alors modifiée.</p></Section></>;
const LegalContent = () => <><Section title="Identification de l’entreprise"><p>Dénomination sociale : {placeholders}. Nom commercial : Uriel Group / Résidence NOEMA. Forme juridique : {placeholders}. Adresse : {placeholders}. Numéro d’enregistrement : {placeholders}.</p></Section><Section title="Publication et hébergement"><p>Responsable de publication : {placeholders}. Hébergeur : {placeholders}, adresse et coordonnées : {placeholders}.</p></Section><Section title="Propriété intellectuelle"><p>Les textes, marques, images, plans, vidéos et éléments graphiques présents sur ce site sont protégés. Toute reproduction ou réutilisation doit être autorisée par le titulaire des droits.</p></Section><Section title="Utilisation et responsabilité"><p>Les informations immobilières et simulations présentées sont indicatives et ne constituent pas une offre bancaire ou un engagement contractuel. Uriel Group s’efforce de maintenir le site à jour, sans garantir l’absence d’erreur ou d’interruption.</p></Section><Section title="Contact"><p>Pour toute question juridique ou commerciale : {placeholders}.</p></Section></>;
const CookieContent = () => <><Section title="Qu’est-ce qu’un cookie ?"><p>Un cookie est un petit fichier enregistré par un site dans le navigateur. Le site utilise aussi la session du navigateur pour certains parcours techniques.</p></Section><Section title="Technologies réellement utilisées"><p>Les cookies Django de session et de protection CSRF sont strictement nécessaires à l’authentification et à la sécurité des requêtes. Les paramètres UTM utilisés pour attribuer une campagne sont conservés dans la session du navigateur, pas dans un cookie.</p><p>La carte Google Maps est affichée comme contenu tiers intégré. Aucun Google Analytics, Google Tag Manager, Meta Pixel ou autre traceur publicitaire n’est installé à ce stade par le site.</p></Section><Section title="Gérer vos préférences"><p>Vous pouvez accepter ou refuser les cookies facultatifs avec le bandeau affiché sur le site. Votre choix est conservé localement dans votre navigateur. La carte reste visible quel que soit votre choix. Pour modifier ce choix, utilisez « Gérer mes cookies » dans le pied de page.</p><button type="button" onClick={() => window.dispatchEvent(new Event('noema-open-cookie-preferences'))} className="font-bold text-[#d15a3a] underline">Gérer mes cookies</button></Section></>;