# Generated by Django 5.1.4 on 2026-09-02 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Référence Lot')),
                ('name', models.CharField(max_length=150, verbose_name='Nom Commercial')),
                ('apartment_type', models.CharField(choices=[('t2', 'T2'), ('t3', 'T3')], default='t2', max_length=30, verbose_name='Typologie')),
                ('rooms_count', models.PositiveSmallIntegerField(default=3, verbose_name='Nombre de pièces')),
                ('bedrooms_count', models.PositiveSmallIntegerField(default=2, verbose_name='Chambres')),
                ('bathrooms_count', models.PositiveSmallIntegerField(default=2, verbose_name="Salles d'eau")),
                ('surface_sqm', models.FloatField(verbose_name='Surface habitable (m²)')),
                ('balcony_surface_sqm', models.FloatField(default=0, verbose_name='Surface terrasse / balcon (m²)')),
                ('floor', models.CharField(max_length=100, verbose_name='Étage / Position')),
                ('price_fcfa', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Prix (FCFA)')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('option', 'Option'), ('reserved', 'Réservé'), ('sold', 'Vendu')], default='available', max_length=20, verbose_name='Statut Commercial')),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('key_features', models.JSONField(blank=True, default=list, verbose_name='Points forts (liste)')),
                ('photos', models.JSONField(blank=True, default=list, verbose_name="Photos (liste d'URLs ou chemins média)")),
                ('floor_plan_image', models.ImageField(blank=True, null=True, upload_to='apartments/plans/', verbose_name="Plan de l'appartement")),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_featured', models.BooleanField(default=True, verbose_name='Mettre en avant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Appartement',
                'verbose_name_plural': 'Appartements',
                'ordering': ['display_order', 'price_fcfa'],
            },
        ),
    ]
