# Generated by Django 5.1.4 on 2026-09-02 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_number', models.PositiveSmallIntegerField(default=1, verbose_name='Étape n°')),
                ('title', models.CharField(max_length=200, verbose_name="Intitulé de l'étape")),
                ('description', models.TextField(verbose_name='Description détaillée des travaux')),
                ('status', models.CharField(choices=[('completed', 'Achevé'), ('in_progress', 'En cours'), ('upcoming', 'À venir')], default='upcoming', max_length=20, verbose_name='Statut')),
                ('progress_percent', models.PositiveSmallIntegerField(default=0, verbose_name='Progression (%)')),
                ('date_display', models.CharField(max_length=100, verbose_name='Date / Période affichée')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='construction/', verbose_name='Photo de chantier réelle')),
                ('is_3d_render', models.BooleanField(default=False, verbose_name='Est un rendu 3D (Transparence acquéreur)')),
                ('video_url', models.URLField(blank=True, verbose_name='Lien vidéo de suivi (optionnel)')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Ordre chronologique')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Avancement Chantier',
                'verbose_name_plural': 'Avancement Chantier',
                'ordering': ['stage_number', 'display_order'],
            },
        ),
    ]
