# Generated by Django 5.1.4 on 2026-09-02 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('phone_whatsapp', models.CharField(max_length=50, verbose_name='Téléphone / WhatsApp')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('residence_country', models.CharField(max_length=100, verbose_name='Pays de résidence')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Âge')),
                ('employment_status', models.CharField(blank=True, max_length=100, verbose_name='Situation professionnelle')),
                ('monthly_net_income', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Revenus mensuels nets')),
                ('down_payment', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Apport personnel disponible')),
                ('existing_monthly_loans', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Crédits / charges existantes')),
                ('desired_duration_years', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Durée souhaitée (ans)')),
                ('interested_apartment_ref', models.CharField(blank=True, max_length=50, verbose_name='Référence appartement')),
                ('simulation_data', models.JSONField(blank=True, default=dict, verbose_name='Données de simulation')),
                ('utm_source', models.CharField(blank=True, max_length=100, verbose_name='Source UTM (ex: instagram, tiktok)')),
                ('utm_medium', models.CharField(blank=True, max_length=100, verbose_name='Medium UTM (ex: cpc, social)')),
                ('utm_campaign', models.CharField(blank=True, max_length=100, verbose_name='Campagne UTM')),
                ('pipeline_stage', models.CharField(choices=[('new', 'Nouveau prospect'), ('qualified', 'Qualifié'), ('contacted', 'Contacté'), ('meeting_scheduled', 'Rendez-vous planifié'), ('file_review', 'Étude du dossier'), ('reserved', 'Réservation'), ('sold', 'Vente conclue')], default='new', max_length=30, verbose_name='Statut Pipeline CRM')),
                ('notes', models.TextField(blank=True, verbose_name='Notes & Historique commercial')),
                ('follow_up_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de relances')),
                ('consent_marketing', models.BooleanField(default=False, verbose_name='Consentement relances marketing')),
                ('consent_data_processing', models.BooleanField(default=True, verbose_name='Consentement traitement données (RGPD)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('interested_apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='apartments.apartment', verbose_name='Appartement ciblé')),
            ],
            options={
                'verbose_name': 'Prospect / Lead CRM',
                'verbose_name_plural': 'Prospects / Leads CRM',
                'ordering': ['-created_at'],
            },
        ),
    ]
