# Generated by Django 5.2.17 on 2026-09-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='additional_monthly_income',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Revenus complémentaires'),
        ),
        migrations.AddField(
            model_name='lead',
            name='ai_conversation_summary',
            field=models.TextField(blank=True, verbose_name='Résumé assistant commercial (le cas échéant)'),
        ),
        migrations.AddField(
            model_name='lead',
            name='co_borrower_monthly_income',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Revenus mensuels co-emprunteur'),
        ),
        migrations.AddField(
            model_name='lead',
            name='funds_availability',
            field=models.CharField(blank=True, choices=[('Disponible immédiatement', 'Disponible immédiatement'), ('Disponible sous 1 à 3 mois', 'Disponible sous 1 à 3 mois'), ('À étudier avec un conseiller', 'À étudier avec un conseiller')], max_length=40, verbose_name='Disponibilité des fonds'),
        ),
        migrations.AddField(
            model_name='lead',
            name='has_co_borrower',
            field=models.BooleanField(default=False, verbose_name='Co-emprunteur'),
        ),
        migrations.AddField(
            model_name='lead',
            name='interested_apartment_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Prix appartement ciblé (au moment de la demande)'),
        ),
        migrations.AddField(
            model_name='lead',
            name='professional_seniority_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ancienneté professionnelle (ans)'),
        ),
        migrations.AddField(
            model_name='lead',
            name='project_purpose',
            field=models.CharField(blank=True, choices=[('Je prépare mon retour à Abidjan', 'Je prépare mon retour à Abidjan'), ('Je construis mon patrimoine en Afrique', 'Je construis mon patrimoine en Afrique'), ('J’investis pour générer des revenus', 'J’investis pour générer des revenus'), ('Je veux mon pied-à-terre à Abidjan et le rentabiliser', 'Je veux mon pied-à-terre à Abidjan et le rentabiliser'), ('Je constitue un patrimoine pour ma famille', 'Je constitue un patrimoine pour ma famille')], max_length=80, verbose_name='Objectif du projet (profil diaspora)'),
        ),
    ]
