# Generated by Django 5.1.4 on 2026-09-02 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Résidence NOEMA', max_length=150, verbose_name='Nom de la résidence')),
                ('tagline', models.CharField(max_length=255, verbose_name='Slogan / Proposition de valeur')),
                ('city', models.CharField(default='Abidjan', max_length=100)),
                ('district', models.CharField(default='Angré Djorogobité', max_length=150)),
                ('country', models.CharField(default="Côte d'Ivoire", max_length=100)),
                ('description', models.TextField(verbose_name='Description architecturale')),
                ('architectural_concept', models.TextField(verbose_name='Concept architectural')),
                ('total_units', models.PositiveIntegerField(default=16, verbose_name='Nombre total de logements')),
                ('floors', models.CharField(default='R+7', max_length=50, verbose_name='Niveaux / Étages')),
                ('delivery_date_estimated', models.CharField(default='T4 2026', max_length=100, verbose_name='Livraison prévisionnelle')),
                ('status', models.CharField(default='Chantier en cours', max_length=100, verbose_name='Statut du programme')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='residences/', verbose_name='Photo principale de la résidence')),
                ('whatsapp_number', models.CharField(default='+2250789001122', max_length=50, verbose_name='Numéro WhatsApp commercial')),
                ('phone_number', models.CharField(default='+225 27 22 00 11 22', max_length=50, verbose_name='Téléphone fixe')),
                ('email_contact', models.EmailField(default='contact@laresidencenoema.com', max_length=254, verbose_name='Email commercial')),
                ('indicative_interest_rate', models.FloatField(default=6.5, verbose_name="Taux d'intérêt indicatif moyen (%)")),
                ('indicative_debt_ratio_limit', models.FloatField(default=33.0, verbose_name="Seuil d'endettement max indicatif (%)")),
                ('address_details', models.TextField(verbose_name='Détails adresse & accès')),
                ('latitude', models.DecimalField(decimal_places=6, default=5.399806, max_digits=9, verbose_name='Latitude GPS')),
                ('longitude', models.DecimalField(decimal_places=6, default=-3.943556, max_digits=9, verbose_name='Longitude GPS')),
            ],
            options={
                'verbose_name': 'Paramètres de la Résidence',
                'verbose_name_plural': 'Paramètres de la Résidence',
            },
        ),
    ]
