# Generated by Django 5.2.17 on 2026-09-15 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0004_update_catalogue_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residence',
            name='delivery_date_estimated',
            field=models.CharField(default='2029-02-09', max_length=100, verbose_name='Livraison prévisionnelle'),
        ),
    ]
