# Generated by Django 5.2.17 on 2026-09-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0011_update_contact_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residence',
            name='email_contact',
            field=models.EmailField(default='finance@urielgroup.fr', max_length=254, verbose_name='Email commercial'),
        ),
        migrations.AlterField(
            model_name='residence',
            name='indicative_debt_ratio_limit',
            field=models.FloatField(default=35.0, verbose_name="Seuil d'endettement max indicatif (%)"),
        ),
        migrations.AlterField(
            model_name='residence',
            name='indicative_interest_rate',
            field=models.FloatField(default=8.0, verbose_name="Taux d'intérêt indicatif moyen (%)"),
        ),
        migrations.AlterField(
            model_name='residence',
            name='whatsapp_number',
            field=models.CharField(default='+377678630862', max_length=50, verbose_name='Numéro WhatsApp commercial'),
        ),
    ]
