# Generated by Django 5.1.4 on 2026-09-02 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('projet', 'Projet & Architecture'), ('financement', 'Financement & Apport'), ('diaspora', 'Acquéreurs Diaspora & Étranger'), ('reservation', 'Réservation & Juridique'), ('chantier', 'Suivi de Chantier & Livraison')], default='projet', max_length=30, verbose_name='Catégorie')),
                ('question', models.CharField(max_length=255, verbose_name='Question fréquente')),
                ('answer', models.TextField(verbose_name='Réponse détaillée')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publiée en ligne')),
            ],
            options={
                'verbose_name': 'Question / Réponse FAQ',
                'verbose_name_plural': 'Questions / Réponses FAQ',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
